
Field Theory Applications in Condensed Matter Physics-III




<!-- wp:paragraph -->
<p>Hi Everyone, this is the fifth and the last post of the <a href="https://everlastingquestforphysics.wordpress.com/2023/08/14/field-theory-applications-in-condensed-matter-physics/">series</a> where we'll discuss some other Statistical Field Theories. In this post,  we'll see  other statistical systems using fields. It's a very vast area but I'll only study Fermi gases and Goldstone bosons. </p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p></p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":4,"style":{"typography":{"fontStyle":"normal","fontWeight":"400"}}} -->
<h4 class="wp-block-heading" style="font-style:normal;font-weight:400"><strong><span style="text-decoration: underline">Fermi Gas</span></strong></h4>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p><br>For a system of N free fermions, we express the Hamiltonian as </p>
<!-- /wp:paragraph -->

<!-- wp:image {"id":1326,"width":664,"height":66,"sizeSlug":"large","linkDestination":"none"} -->
<figure class="wp-block-image size-large is-resized"><img src="https://everlastingquestforphysics.files.wordpress.com/2023/08/lagrida_latex_editor-4-9.png?w=189" alt="" class="wp-image-1326" style="width:664px;height:66px" width="664" height="66" /></figure>
<!-- /wp:image -->

<!-- wp:paragraph -->
<p>, where |α⟩ forms a basis for a complete set of one-particle states. The index labels these states in ascending order of energies, such that E<sub>1</sub>&lt;E<sub>2</sub>&lt;... . Since fermions obey the exclusion principle, only one fermion can occupy each state. Consequently, the state with the lowest energy is achieved by filling the first N single-particle states. This lowest-energy state is denoted as |Ground⟩.</p>
<!-- /wp:paragraph -->

<!-- wp:image {"id":1213,"width":664,"height":91,"sizeSlug":"large","linkDestination":"none"} -->
<figure class="wp-block-image size-large is-resized"><img src="https://everlastingquestforphysics.files.wordpress.com/2023/08/lagrida_latex_editor-3-7.png?w=428" alt="" class="wp-image-1213" style="width:664px;height:91px" width="664" height="91" /></figure>
<!-- /wp:image -->

<!-- wp:paragraph -->
<p> The energy of this state is giveb by </p>
<!-- /wp:paragraph -->

<!-- wp:image {"id":1223,"width":664,"height":36,"sizeSlug":"large","linkDestination":"none"} -->
<figure class="wp-block-image size-large is-resized"><img src="https://everlastingquestforphysics.files.wordpress.com/2023/08/lagrida_latex_editor-3-8.png?w=267" alt="" class="wp-image-1223" style="width:664px;height:36px" width="664" height="36" /></figure>
<!-- /wp:image -->

<!-- wp:paragraph -->
<p>. The energy of the top-most occupied single particle state E<sub>N</sub>, is called the <strong>Fermi energy of the system</strong> and the set of occupied states is called the <strong>Fermi sea</strong>.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>An excited state is generated by extracting a particle from the single-particle state N, thereby creating a "hole," and placing the particle into the vacant single-particle state N+1. This configuration constitutes a state characterized by a single particle-hole pair.</p>
<!-- /wp:paragraph -->

<!-- wp:image {"id":1219,"width":664,"height":71,"sizeSlug":"large","linkDestination":"none"} -->
<figure class="wp-block-image size-large is-resized"><img src="https://everlastingquestforphysics.files.wordpress.com/2023/08/lagrida_latex_editor-1-12.png?w=436" alt="" class="wp-image-1219" style="width:664px;height:71px" width="664" height="71" /></figure>
<!-- /wp:image -->

<!-- wp:paragraph -->
<p>The energy associated with this state is given by </p>
<!-- /wp:paragraph -->

<!-- wp:image {"id":1328,"width":664,"height":39,"sizeSlug":"large","linkDestination":"none"} -->
<figure class="wp-block-image size-large is-resized"><img src="https://everlastingquestforphysics.files.wordpress.com/2023/08/lagrida_latex_editor-5-11.png?w=324" alt="" class="wp-image-1328" style="width:664px;height:39px" width="664" height="39" /></figure>
<!-- /wp:image -->

<!-- wp:paragraph -->
<p>. The difference between this energy and the ground state energy is the excitation energy, denoted as </p>
<!-- /wp:paragraph -->

<!-- wp:image {"id":1329,"width":664,"height":39,"sizeSlug":"large","linkDestination":"none"} -->
<figure class="wp-block-image size-large is-resized"><img src="https://everlastingquestforphysics.files.wordpress.com/2023/08/lagrida_latex_editor-6-7.png?w=247" alt="" class="wp-image-1329" style="width:664px;height:39px" width="664" height="39" /></figure>
<!-- /wp:image -->

<!-- wp:paragraph -->
<p>Using |Ground⟩ instead of |0⟩ as the reference state is a more suitable choice. An operator</p>
<!-- /wp:paragraph -->

<!-- wp:image {"id":1221,"width":664,"height":43,"sizeSlug":"large","linkDestination":"none"} -->
<figure class="wp-block-image size-large is-resized"><img src="https://everlastingquestforphysics.files.wordpress.com/2023/08/lagrida_latex_editor-2-9.png?w=116" alt="" class="wp-image-1221" style="width:664px;height:43px" width="664" height="43" /></figure>
<!-- /wp:image -->

<!-- wp:paragraph -->
<p>is introduced. Due to the fermionic nature of these operators, they satisfy the anticommutation relations </p>
<!-- /wp:paragraph -->

<!-- wp:image {"id":1335,"width":664,"height":42,"sizeSlug":"large","linkDestination":"none"} -->
<figure class="wp-block-image size-large is-resized"><img src="https://everlastingquestforphysics.files.wordpress.com/2023/08/lagrida_latex_editor-9-7.png?w=302" alt="" class="wp-image-1335" style="width:664px;height:42px" width="664" height="42" /></figure>
<!-- /wp:image -->

<!-- wp:image {"id":1333,"width":664,"height":47,"sizeSlug":"large","linkDestination":"none"} -->
<figure class="wp-block-image size-large is-resized"><img src="https://everlastingquestforphysics.files.wordpress.com/2023/08/lagrida_latex_editor-8-10.png?w=289" alt="" class="wp-image-1333" style="width:664px;height:47px" width="664" height="47" /></figure>
<!-- /wp:image -->

<!-- wp:paragraph -->
<p>With respect to |Ground⟩, </p>
<!-- /wp:paragraph -->

<!-- wp:image {"id":1336,"width":664,"height":43,"sizeSlug":"large","linkDestination":"none"} -->
<figure class="wp-block-image size-large is-resized"><img src="https://everlastingquestforphysics.files.wordpress.com/2023/08/lagrida_latex_editor-12-5.png?w=52" alt="" class="wp-image-1336" style="width:664px;height:43px" width="664" height="43" /></figure>
<!-- /wp:image -->

<!-- wp:paragraph -->
<p> and </p>
<!-- /wp:paragraph -->

<!-- wp:image {"id":1337,"width":664,"height":51,"sizeSlug":"large","linkDestination":"none"} -->
<figure class="wp-block-image size-large is-resized"><img src="https://everlastingquestforphysics.files.wordpress.com/2023/08/lagrida_latex_editor-13-4.png?w=48" alt="" class="wp-image-1337" style="width:664px;height:51px" width="664" height="51" /></figure>
<!-- /wp:image -->

<!-- wp:paragraph -->
<p>act as creation operators for electrons and holes, respectively. An arbitrary excited state can be expressed in the form:</p>
<!-- /wp:paragraph -->

<!-- wp:image {"id":1218,"width":664,"height":47,"sizeSlug":"large","linkDestination":"none"} -->
<figure class="wp-block-image size-large is-resized"><img src="https://everlastingquestforphysics.files.wordpress.com/2023/08/lagrida_latex_editor-26.png?w=479" alt="" class="wp-image-1218" style="width:664px;height:47px" width="664" height="47" /></figure>
<!-- /wp:image -->

<!-- wp:paragraph -->
<p>This state contains m electrons and n holes, where m is always equal to n. In contrast, the ground state is annihilated by </p>
<!-- /wp:paragraph -->

<!-- wp:image {"id":1339,"width":664,"height":35,"sizeSlug":"large","linkDestination":"none"} -->
<figure class="wp-block-image size-large is-resized"><img src="https://everlastingquestforphysics.files.wordpress.com/2023/08/lagrida_latex_editor-14-3.png?w=54" alt="" class="wp-image-1339" style="width:664px;height:35px" width="664" height="35" /></figure>
<!-- /wp:image -->

<!-- wp:paragraph -->
<p><em> and </em></p>
<!-- /wp:paragraph -->

<!-- wp:image {"id":1341,"width":664,"height":45,"sizeSlug":"large","linkDestination":"none"} -->
<figure class="wp-block-image size-large is-resized"><img src="https://everlastingquestforphysics.files.wordpress.com/2023/08/lagrida_latex_editor-15-3.png?w=50" alt="" class="wp-image-1341" style="width:664px;height:45px" width="664" height="45" /></figure>
<!-- /wp:image -->

<!-- wp:paragraph -->
<p>.</p>
<!-- /wp:paragraph -->

<!-- wp:image {"id":1217,"width":664,"height":46,"sizeSlug":"large","linkDestination":"none"} -->
<figure class="wp-block-image size-large is-resized"><img src="https://everlastingquestforphysics.files.wordpress.com/2023/08/lagrida_latex_editor-4-6.png?w=324" alt="" class="wp-image-1217" style="width:664px;height:46px" width="664" height="46" /></figure>
<!-- /wp:image -->

<!-- wp:paragraph -->
<p>The Hamiltonian is normally ordered with respect to the vacuum state, i.e., </p>
<!-- /wp:paragraph -->

<!-- wp:image {"id":1344,"width":664,"height":46,"sizeSlug":"large","linkDestination":"none"} -->
<figure class="wp-block-image size-large is-resized"><img src="https://everlastingquestforphysics.files.wordpress.com/2023/08/lagrida_latex_editor-16-2.png?w=115" alt="" class="wp-image-1344" style="width:664px;height:46px" width="664" height="46" /></figure>
<!-- /wp:image -->

<!-- wp:paragraph -->
<p>, but it is not normally ordered with respect to the ground state. The particle-hole transformation allows us to express this as:</p>
<!-- /wp:paragraph -->

<!-- wp:image {"id":1216,"width":664,"height":68,"sizeSlug":"large","linkDestination":"none"} -->
<figure class="wp-block-image size-large is-resized"><img src="https://everlastingquestforphysics.files.wordpress.com/2023/08/lagrida_latex_editor-2-8.png?w=485" alt="" class="wp-image-1216" style="width:664px;height:68px" width="664" height="68" /></figure>
<!-- /wp:image -->

<!-- wp:paragraph -->
<p>The number operator is given by</p>
<!-- /wp:paragraph -->

<!-- wp:image {"id":1215,"width":664,"height":68,"sizeSlug":"large","linkDestination":"none"} -->
<figure class="wp-block-image size-large is-resized"><img src="https://everlastingquestforphysics.files.wordpress.com/2023/08/lagrida_latex_editor-1-11.png?w=379" alt="" class="wp-image-1215" style="width:664px;height:68px" width="664" height="68" /></figure>
<!-- /wp:image -->

<!-- wp:paragraph -->
<p>Electrons contribute to an increase in energy, whereas holes lead to a reduction in energy. Enforcing the requirement that the Hamiltonian conserves particle number, i.e., </p>
<!-- /wp:paragraph -->

<!-- wp:image {"id":1346,"width":664,"height":46,"sizeSlug":"large","linkDestination":"none"} -->
<figure class="wp-block-image size-large is-resized"><img src="https://everlastingquestforphysics.files.wordpress.com/2023/08/lagrida_latex_editor-17-2.png?w=131" alt="" class="wp-image-1346" style="width:664px;height:46px" width="664" height="46" /></figure>
<!-- /wp:image -->

<!-- wp:paragraph -->
<p>, reveals that when a particle is removed, a hole must be generated. Consequently, particles and holes are created in pairs.</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":4,"style":{"typography":{"fontStyle":"normal","fontWeight":"400"}}} -->
<h4 class="wp-block-heading" style="font-style:normal;font-weight:400"><strong><span style="text-decoration: underline">Goldstone Bosons</span></strong></h4>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p><br>The different phases of matter can be distinguished by two distinct symmetry groups  G that pertains to the symmetry of the system's free energy, and H that corresponds to the symmetry of the ground state.</p>
<!-- /wp:paragraph -->

<!-- wp:image {"id":1324,"sizeSlug":"large","linkDestination":"none"} -->
<figure class="wp-block-image size-large"><img src="https://everlastingquestforphysics.files.wordpress.com/2023/08/image-26.png?w=1024" alt="" class="wp-image-1324" /></figure>
<!-- /wp:image -->

<!-- wp:paragraph -->
<p>This structure is evident in the Ising model. When B=0, the free energy exhibits a <strong>Z</strong><sub>2</sub> symmetry. In the disordered phase, this symmetry remains unaltered—both the Hamiltonian H and the system possess a <strong>Z</strong><sub>2</sub> symmetry. However, in the ordered phase, the symmetry is spontaneously broken as the system selects one of two possible ground states. In this scenario, the Hamiltonian H does not possess any symmetry group.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>When a discrete symmetry group undergoes spontaneous breaking, it gives rise to several distinct ground states. Transitioning from one ground state to another becomes possible by applying the generators of G that have been broken. The various phases of matter falling under this category are defined by the nature of H. Consequently, a phase transition occurs whenever there is a change in H.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>The concept of spontaneous symmetry breaking in condensed matter systems can be illustrated using the theory of N real scalar fields featuring an O(N) symmetry. Specifically, models with N=2 fall into the XY-universality class. This framework effectively describes phenomena such as <strong>Bose-Einstein condensates</strong> and superfluids.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>Pairing the two real fields into a single complex field <strong>ψ =φ<sub>1</sub>+iφ<sub>2</sub></strong> proves to be a convenient approach. This pairing maintains invariance under U(1) transformations, where ψ' remains unchanged when subjected to e<sup>iθ</sup>ψ . Unlike the Ising model with only two potential ground states, continuous symmetries introduce an array of infinitely many ground states.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>The minimum of the free energy imposes a constraint solely on the magnitude of ψ, resulting in </p>
<!-- /wp:paragraph -->

<!-- wp:image {"id":1358,"width":664,"height":85,"sizeSlug":"large","linkDestination":"none"} -->
<figure class="wp-block-image size-large is-resized"><img src="https://everlastingquestforphysics.files.wordpress.com/2023/08/lagrida_latex_editor-25-1.png?w=235" alt="" class="wp-image-1358" style="width:664px;height:85px" width="664" height="85" /></figure>
<!-- /wp:image -->

<!-- wp:paragraph -->
<p>. Yet, the process of minimizing the free energy doesn't ascertain the specific direction of ψ . Consequently, a range of ground state possibilities is left, forming a sphere known as </p>
<!-- /wp:paragraph -->

<!-- wp:image {"id":1360,"width":664,"height":71,"sizeSlug":"large","linkDestination":"none"} -->
<figure class="wp-block-image size-large is-resized"><img src="https://everlastingquestforphysics.files.wordpress.com/2023/08/lagrida_latex_editor-26-1.png?w=208" alt="" class="wp-image-1360" style="width:664px;height:71px" width="664" height="71" /></figure>
<!-- /wp:image -->

<!-- wp:paragraph -->
<p>. Broadly speaking, the manifold of ground states takes the form </p>
<!-- /wp:paragraph -->

<!-- wp:image {"id":1362,"width":664,"height":63,"sizeSlug":"large","linkDestination":"none"} -->
<figure class="wp-block-image size-large is-resized"><img src="https://everlastingquestforphysics.files.wordpress.com/2023/08/lagrida_latex_editor-27-1.png?w=58" alt="" class="wp-image-1362" style="width:664px;height:63px" width="664" height="63" /></figure>
<!-- /wp:image -->

<!-- wp:paragraph -->
<p>. Each point on this sphere characterizes a distinct direction for ψ while sharing the same energy.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>Exploring configurations that remain within the realm of ground states while allowing variations in direction across space is possible. In these configurations, a portion of the free energy </p>
<!-- /wp:paragraph -->

<!-- wp:image {"id":1355,"width":664,"height":42,"sizeSlug":"large","linkDestination":"none"} -->
<figure class="wp-block-image size-large is-resized"><img src="https://everlastingquestforphysics.files.wordpress.com/2023/08/lagrida_latex_editor-23-1.png?w=235" alt="" class="wp-image-1355" style="width:664px;height:42px" width="664" height="42" /></figure>
<!-- /wp:image -->

<!-- wp:paragraph -->
<p> continues to be minimized. However, contributions from gradient terms </p>
<!-- /wp:paragraph -->

<!-- wp:image {"id":1357,"width":664,"height":38,"sizeSlug":"large","linkDestination":"none"} -->
<figure class="wp-block-image size-large is-resized"><img src="https://everlastingquestforphysics.files.wordpress.com/2023/08/lagrida_latex_editor-24-1.png?w=104" alt="" class="wp-image-1357" style="width:664px;height:38px" width="664" height="38" /></figure>
<!-- /wp:image -->

<!-- wp:paragraph -->
<p> become pertinent in such cases.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p><mark style="background-color:#d6c93b" class="has-inline-color">Excitations that emerge due to the spontaneous breaking of continuous symmetries are referred to as Goldstone bosons</mark>. The count of Goldstone bosons is determined by </p>
<!-- /wp:paragraph -->

<!-- wp:image {"id":1352,"width":664,"height":39,"sizeSlug":"large","linkDestination":"none"} -->
<figure class="wp-block-image size-large is-resized"><img src="https://everlastingquestforphysics.files.wordpress.com/2023/08/lagrida_latex_editor-20-2.png?w=201" alt="" class="wp-image-1352" style="width:664px;height:39px" width="664" height="39" /></figure>
<!-- /wp:image -->

<!-- wp:paragraph -->
<p>. In the case of O(N) models, this count equals </p>
<!-- /wp:paragraph -->

<!-- wp:image {"id":1353,"width":664,"height":62,"sizeSlug":"large","linkDestination":"none"} -->
<figure class="wp-block-image size-large is-resized"><img src="https://everlastingquestforphysics.files.wordpress.com/2023/08/lagrida_latex_editor-21-1.png?w=430" alt="" class="wp-image-1353" style="width:664px;height:62px" width="664" height="62" /></figure>
<!-- /wp:image -->

<!-- wp:paragraph -->
<p>, which coincides with the dimensionality of <strong>S<sup>N-1</sup></strong>.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>In the context of the XY class, during the ordered phase, the resulting free energy follows the aforementioned pattern. Notably, a circle of minima represented by <strong>S<sup>1</sup></strong> emerges. By expressing <strong>ψ(x)</strong> as </p>
<!-- /wp:paragraph -->

<!-- wp:image {"id":1350,"width":664,"height":44,"sizeSlug":"large","linkDestination":"none"} -->
<figure class="wp-block-image size-large is-resized"><img src="https://everlastingquestforphysics.files.wordpress.com/2023/08/lagrida_latex_editor-19-2.png?w=131" alt="" class="wp-image-1350" style="width:664px;height:44px" width="664" height="44" /></figure>
<!-- /wp:image -->

<!-- wp:paragraph -->
<p>and defining </p>
<!-- /wp:paragraph -->

<!-- wp:image {"id":1348,"width":664,"height":43,"sizeSlug":"large","linkDestination":"none"} -->
<figure class="wp-block-image size-large is-resized"><img src="https://everlastingquestforphysics.files.wordpress.com/2023/08/lagrida_latex_editor-18-2.png?w=227" alt="" class="wp-image-1348" style="width:664px;height:43px" width="664" height="43" /></figure>
<!-- /wp:image -->

<!-- wp:paragraph -->
<p>, the free energy assumes the following form:</p>
<!-- /wp:paragraph -->

<!-- wp:image {"id":1214,"sizeSlug":"large","linkDestination":"none"} -->
<figure class="wp-block-image size-large"><img src="https://everlastingquestforphysics.files.wordpress.com/2023/08/lagrida_latex_editor-25.png?w=728" alt="" class="wp-image-1214" /></figure>
<!-- /wp:image -->

<!-- wp:paragraph -->
<p> where φ is the Goldstone boson.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p></p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":4,"style":{"typography":{"fontStyle":"normal","fontWeight":"400"}}} -->
<h4 class="wp-block-heading" style="font-style:normal;font-weight:400"><strong><span style="text-decoration: underline">References</span></strong></h4>
<!-- /wp:heading -->

<!-- wp:list {"ordered":true} -->
<ol><!-- wp:list-item -->
<li><strong>Field Theoretic Aspects of Condensed Matter Physics: An Overview</strong>,  <a href="https://arxiv.org/search/cond-mat?searchtype=author&amp;query=Fradkin%2C+E">Eduardo Fradkin</a></li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li><strong><a href="https://arxiv.org/pdf/2110.14504">An introduction to Goldstone boson physics and to the coset construction</a></strong> , Daniel Naegels</li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li><strong><a href="https://indico.cern.ch/event/216537/contributions/1515832/attachments/346304/482951/CERN_lect_Boos2.pdf">Quantum Field Theory and the Electroweak Standard Model</a></strong>, E.E Boos, CERN</li>
<!-- /wp:list-item --></ol>
<!-- /wp:list -->

<!-- wp:paragraph -->
<p></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p></p>
<!-- /wp:paragraph -->
